<div id="pack-popup-container" class="sng-pack-popup-container">
    <div class="sng-pack-popup-inner">
        <!-- Actual container -->
        <div class="sng-pack-popup">
            <!-- Top-right button to close popup -->
            <a id="close-btn" class="sng-close-btn"><i class="fa fa-close"></i></a>

            <h1 class="sng-headers sng-w-1-1 sng-padding-top">Riepilogo</h1>
            <div class="sng-separator-line"></div>

            <div class="sng-summary">
                <h2 class="sng-headers">Descrizione:</h2>
                <p id="description" class="sng-text"><?= $this->package->getDescription() ?></p>

                <table class="sng-table">
                    <tr>
                        <td class="sng-w-1-2">
                            <h2>Minuti:</h2>
                            <p id="minutes" class="sng-text"><?= $this->package->getMinutes() ?></p>
                        </td>
                        <td class="sng-w-1-2">
                            <h2>Prezzo:</h2>
                            <p id="cost" class="sng-text">€ <?= number_format($this->package->getCost() / 100, 2, ',', '.') ?></p>
                        </td>
                    </tr>
                    <tr>
                        <td class="sng-w-1-2">
                            <h2>Valido dal:</h2>
                            <p id="valid-from" class="sng-text"><?= date_create()->format('d-m-Y') ?></p>
                        </td>
                        <td class="sng-w-1-2">
                            <h2>Valido al:</h2>
                            <p id="valid-to" class="sng-text"><?= sprintf($this->translate("per %d gg"), $this->package->getDuration()); ?></p>
                        </td>
                    </tr>
                    <tr>
                        <td class="sng-w-1-2">
                            <h2>Disponibile fino al:</h2>
                            <p id="available-until" class="sng-text"><?= $this->package->getBuyableUntil()->format('d-m-Y') ?></p>
                        </td>
                    </tr>
                </table>

            </div>

            <div class="sng-footer">
                <?php if ($this->hasContract): ?>
                    <p class="sng-text">Confermare l'acquisto utilizzando Cartasi?</p>
                    <button id="confirm-btn" class="big green" data-href="<?= $this->url('area-utente/buy-package') ?>" data-package-id="<?= $this->package->getId() ?>">Conferma</button>
                <?php else: ?>
                    <p class="sng-text">Confermare l'acquisto registrando una carta di credito con Cartasi</p>
                    <a id="confirm-btn" class="big green" href="<?= $this->url('cartasi/primo-pagamento-pacchetto', ['package' => $this->package->getId()]) ?>">Conferma</a>
                <?php endif; ?>
            </div>

        </div>
        <!-- actual container -->
    </div>
</div>
