<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

    <!-- Bootstrap -->
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    <link href="/aeronautica/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/aeronautica/application/images/aeronautica-top.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/aeronautica/application/images/aeronautica-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
                <p class="white strong">
                    <span id="intro strong lato-bold">Se è in forza all’Aeronautica Militare di Firenze o uno studente dell’ISMA o della scuola Giulio Douhet</span>
                </p>
                <p class="yellow" id="paragraph1">
                    <span class="strong lato-regular">con un click e 5 € usa a FIRENZE le Equomobili elettriche e condivise di <span class="strong-big lato-bold">SHARE'NGO</span> con 30 minuti gratis e il 20% di sconto!
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/aeronautica/application/images/aeronautica-top.jpg" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/aeronautica/application/images/aeronautica-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 text-center p-top-5" id="second-paragraph">
                <a href="<?= $this->url('promocode-signup',['promocode' => 'AERO']); ?>" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'AERO'});">
                    <p class="yellow semistrong">
                        <span class="lato-bold">
                               <strong class="strong-big2">SI REGISTRI OGGI.</strong>
                        </span><br>
                        <span class="lato-regular">Le nostre auto sono pronte</span>
                        <span class="lato-regular">all’uscita dell’ISMA.</span><br>
                        <span class="white lato-regular">CODICE PROMO</span>
                    </p>
                    <button class="strong">AERO</button>
                </a>
            </div>
        </div>
    </div>
</body>