<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/bikemi/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>

</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
                <p class="white strong">
                    <span id="intro">Se sei abbonato a</span>
                    <div id="logo"></div>
                </p>
                <p class="black" id="paragraph1">
                    <span class="strong desk-block lato-regular">Con  un click</span>
                    <span class="strong desk-block lato-regular">e <span class="lato-bold">1 €</span> usi anche</span>
                    <span class="strong desk-block lato-regular">le Equomobili di</span>
                    <span class="strong desk-block lato-bold">SHARE'NGO</span>
                    <span class="strong desk-block lato-regular">con 100 minuti gratis!</span>
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/bikemi/application/images/bikeMI-top.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/bikemi/application/images/bikeMI-top.jpg" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/bikemi/application/images/bikeMI-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/bikemi/application/images/bikeMI-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 text-center p-top-5" id="second-paragraph">
                <p class="red strong" id="registrati">
                    <a href="http://www.equomobili.it/?codice_sconto=BKGO" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'BKGO 1'});">
                        <span>Registrati oggi</span>
                        <span>su www.equomobili.it</span>
                        <span>con il CODICE PROMO</span>
                    </a>
                </p>
                <a href="http://www.equomobili.it/?codice_sconto=BKGO" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'BKGO 2'});" id="submit">
                    <button class="semistrong">BKGO</button>
                </a>
                <p class="black strong">
                    <span class="lato-bold">LE EQUOMOBILI</span>
                    <span class="lato-bold">DI SHARE’NGO</span>
                    <span class="lato-bold">PI&Uacute NE HAI BISOGNO</span>
                    <span class="lato-bold">E MENO COSTANO</span>
                </p>
                <p class="black semistrong">
                    <span class="lato-regular">E DI NOTTE LE CORSE</span>
                    <span class="lato-regular">PER LE DONNE SONO GRATIS</span>
                    <span class="lato-regular">(dalle ore 1:00 alle 6:00 del mattino).</span>
                </p>
            </div>
        </div>
    </div>
</body>