<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/eq-sharing/application/css/style.css" rel="stylesheet">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');

    </script>
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-5 col-sm-push-7 text-center">
                <p class="white strong">
                    <span>Sei socio di</span>
                    <span class="desk-block desk-inline">EQ SHARING?</span>
                </p>
                <p class="yellow">
                    <span class="strong desk-block">Con  un click e 1 &euro; </span>
                    <span class="strong desk-block">passi a SHARE'NGO </span>
                    <span class="semistrong">con 100 minuti gratis</span>
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-1.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-3.jpg" class="img-responsive"/>
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-2.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-4.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-5 text-center p-top-5">
                <p class="white smaller">Dal 15 settembre SHARE'NGO subentra ad EQ SHARING nella gestione del servizio di car sharing elettrico delle Isole Digitali con oltre 300 quadricicli ZD ad alte prestazioni (80 kmh, 120 km di autonomia).</p>
                <p class="yellow semistrong">
                    <a href="http://www.equomobili.it/?codice_sconto=EQZD" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'EQZD 1'});">
                        <span>Registrati entro il 15/10</span>
                        <span>a SHARE'NGO su</span>
                        <span class="desk-block">www.equomobili.it</span>
                    </a>
                        <span>con il CODICE PROMO</span>
                </p>
                <a href="http://www.equomobili.it/?codice_sconto=EQZD" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'EQZD 2'});">
                    <button class="semistrong">EQZD</button>
                </a>
                <p class="white semistrong">L'ISCRIZIONE AL SERVIZIO E I PRIMI 100 MINUTI TI COSTERANNO SOLO 1 EURO!</p>
            </div>
        </div>
    </div>
</body>
