<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

         <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/express/application/css/style.css" rel="stylesheet">

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-63160906-2', 'auto');
          ga('send', 'pageview');
        </script>
    </head>
    <body class="bg-grey">
    	<div class="container-fluid lato-bold">
    		<div class="col-sm-12 bg-grey">
                <div class="col-sm-7 col-sm-pull-5 img-mobile">
                    <img src="/express/application/images/express-top.jpg" class="img-responsive"/>
                </div>
                <div class="col-sm-7 img-mobile">
                    <img src="/express/application/images/express-bottom.jpg" class="img-responsive"/>
                </div>
    			<div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
    				<p class="white" id="paragraph1">
                        <span class="strong desk-block lato-regular">Con un click e 5€ i clienti Express</span>
                        <span class="strong desk-block lato-regular">di MILANO, FIRENZE e ROMA</span>
                        <span class="strong desk-block lato-regular">usano le auto elettriche</span>
                        <span class="strong desk-block lato-regular">e condivise di SHARE'NGO</span>
                        <span class="strong desk-block lato-regular">con 30 minuti gratis</span>
                        <span class="strong desk-block lato-regular">e il 20% di sconto!</span>
                    </p>
    			</div>
    			<div class="col-sm-7 col-sm-pull-5 img-desk">
    				<img src="/express/application/images/express-top.jpg" class="img-responsive"/>
    			</div>
    		</div>
    		<div class="col-sm-12 bg-grey">
    			<div class="col-sm-7 img-desk">
    				<img src="/express/application/images/express-bottom.jpg" class="img-responsive"/>
    			</div>
    			<div class="col-sm-5 text-center p-top-5" id="second-paragraph">
    				<p class="yellow strong" id="registrati">
    					<span class="lato-bold">REGISTRATI OGGI<br/></span>
                        <span class="lato-bold">CON IL CODICE PROMO</span>
    				</p>
                    <a href="<?= $this->url('promocode-signup',['promocode' => 'EXPR16']); ?>" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'EXPR16'});">
                         <button class="strong">EXPR16</button>
					</a>
                    <p></p>
                    <p class="white strong" id="paragraph2">
                        <span class="lato-regular">Con la mobilit&agrave; sostenibile</span>
                        <span class="lato-regular">le nostre citt&agrave;</span>
                        <span class="lato-regular">saranno sempre pi&ugrave; vivibili.</span>
                    </p>
    			</div>
    		</div>
    	</div>
    </body>
