<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/fao/application/css/style.css" rel="stylesheet">

        <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-blue">
        <div class="container-fluid lato-bold">
            <div class="row bg-grey  bg-blue">
                <div class="col-lg-6 col-md-7" style="padding-left: 0px">
                   <img src="/fao/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
                <div class="col-lg-6 col-md-5 text-center" >
                    <div id="first-paragraph">
                        <span class="lato-regular strong white">
                            For
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        <span class="impact strong-more-big white">FAO STAFF COOP</span>
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        members only</span>
                        <p></p>
                        <span class="lato-regular strong white">
                            You register to SHARE’NGO
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            for <span class="lato-bold white">5€ instead of 10€</span>
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            Get <span class="lato-bold white">100 minutes run bonus</span>
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            and you drive at a flat rate
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            with <span class="lato-bold white">35% savings</span> (0,18€/minute)
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            in Rome, Florence and Milan.
                        </span>
                        <p></p>
                        <span class="lato-regular strong-big white">ENROL NOW</span></a>
                        <p></p>
                        <div class="text-center">
                            <span class="strong-small desk-block lato-regular white">PROMO CODE</span>
                            <a href="<?= $this->url('promocode-signup',['promocode' => 'FAO']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'FAO'});">FAO</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>