<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

    <!-- Bootstrap -->
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    <link href="/firenze/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
                <div id="logo">
                    <div id="logo-fi"></div>
                    <div id="logo-eu"></div>
                    <div id="logo-electra"></div>
                </div>
                <p class="dark-gray" id="paragraph1a">
                    <span class="strong desk-block lato-bold">CON ELE.C.TRA</span>
                    <span class="strong desk-block lato-bold">E SHARE’NGO</span>
                    <span class="strong desk-block lato-bold">IL TUO GIRO</span>
                    <span class="strong desk-block lato-bold">DI PROVA</span>
                    <span class="strong desk-block lato-bold">COSTA SOLO 1 €</span>
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/firenze/application/images/electra-top.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/firenze/application/images/electra-top.jpg" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/firenze/application/images/electra-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/firenze/application/images/electra-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 text-center p-top-5" id="second-paragraph">
                <p class="dark-gray strong" id="registrati">
                    <a href="http://www.equomobili.it/?codice_sconto=FITEST" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'FITEST 1'});">
                        <span class="lato-regular">ISCRIVITI OGGI SU</span>
                        <span class="lato-regular">www.sharengo.it/firenze</span>
                        <br>
                        <span class="lato-regular">CON IL CODICE PROMO</span>
                    </a>
                </p>
                <a href="http://www.equomobili.it/?codice_sconto=FITEST" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'FITEST 2'});">
                    <button class="strong">FITEST</button>
                </a>
                <p class="dark-gray small lato-regular" id="nota">Se il giro di prova ti sarà piaciuto, aggiungendo 9 €, completerai l’iscrizione, avrai altri 100 minuti gratuiti e potrai usare le Equomobili di Share’ngo ogni volta che vorrai, con la tua tariffa personalizzata. <span class="lato-bold">Perchè Share’ngo, più ne hai bisogno... e meno costa.</span></p>
            </div>
        </div>
    </div>
</body>