<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/legambiente/application/css/style.css" rel="stylesheet">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body class="bg-blue">
    	<div class="container-fluid lato-bold">
    		<div class="row bg-grey  bg-blue">
                <div class="col-lg-7 col-md-8">
                    <img src="/legambiente/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
    			<div class="col-lg-5 col-md-4 text-center" >
                    <div id="first-paragraph">
        				<p class="white" id="paragraph1">
                        	<br class="visible-md visible-lg">
                            <br class="visible-md visible-lg">
                            <br class="visible-md visible-lg">
                            <span class="lato-regular strong-big">
                            <span class="lato-bold">IL CAR SHARING ELETTRICO<br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">CAMBIA LE NOSTRE CITT&Agrave;.
                            </span><br class="visible-md visible-lg"></p>
                            <p>
                            <span class="lato-regular strong-small grey"><span class="lato-bold">
                            E I SOCI E GLI AMICI DI LEGAMBIENTE<br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">DI MILANO, FIRENZE e ROMA
							</span>
                            </p>
                            <p>
                            <span class="lato-regular strong-small grey"><span class="lato-bold">
                            VIAGGIANO CON IL 25% DI SCONTO<br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">(21 cent./minuto) E 30 MINUTI BONUS</span>
                            </span>
							</p>
                        </p>
						<br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
                        <span class="lato-regular strong-big white">
                            ISCRIVITI OGGI CON €5<br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">E IL CODICE PROMO
                        </span>
                        <div class="text-center space">
                            <a href="<?= $this->url('promocode-signup',['promocode' => 'LEGAMB']); ?>" id="submit" class="button">LEGAMB</a>
                        </div>
                        <p class="white" id="paragraph1a">
                            <span class="strong-too-small desk-block lato-regular">
                                Aderendo alla convenzione autorizzo SHARE’NGO a informarne Legambiente
                            </span>
                        </p>
                    </div>
    			</div>
    		</div>
    	</div>
    </body>
