<?php
    // get data
    $customer = $this->customer;
    $isActivated = $this->isActivated;
    $tripPayment = $this->tripPayment;

    // parse data
    $name = ucwords(strtolower($customer->getName() . ' ' . $customer->getSurname()));
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', ['route' => 'activate-payments']); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Attivazione pagamenti'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume content -->
                <div class="module-sharing-resmume padding-top">

                    <?php
                        // check if customer has no credit card
                        if (!$isActivated) {
                            // check if customer has trips
                            if ($tripPayment != null) {
                    ?>

                    <!-- Description -->
                    <div>
                        <p>Ciao <?= $name ?>,</p>
                        <p>come puoi vedere nella sezione <a href="<?= $this->url('area-utente/rents') ?>">Le mie corse</a> hai esaurito i tuoi minuti bonus e hai effettuato una o più corse "a debito".</p>
                        <p>Ti eri iscritto/a a Share’ngo regolando il pagamento dell'iscrizione con paypal o con bonifico.</p>
                        <p>Per questo ti invitiamo ad effettuare il pagamento di quanto a noi dovuto con un carta di credito valida (anche pre-pagata) scegliendo così la carta che vuoi associare in modo permanente al tuo profilo cliente.</p>
                        <p>Dopo questo primo pagamento le corse ti saranno addebitate periodicamente in automatico su questa carta e potrai scaricare le fatture nella sezione <a href="<?= $this->url('area-utente/invoices-list') ?>">Fatture</a> il giorno successivo all'addebito.</p>

                        <p><br>Attenzione: nel caso in cui il tuo debito non venisse saldato - e non avessimo quindi una carta di credito valida associata al tuo profilo utente - il tuo account sarà sospeso fino al pagamento (potrai accedere all’area riservata ma non fare il log-in sulla APP o utilizzare un’Equomobile di Share’ngo).</p>

                        <h2 class="margin-top-custom">Di seguito i dettagli della corsa di cui effettuare il pagamento:</h2>
                    </div>
                    <!-- description -->

                    <!-- Trip table -->
                    <div class="block-data-table clearboth clearfix margin-top-custom">

                        <!-- Trip table headers -->
                        <div class="block-data-table-row clearfix">
                            <div class="block-data-table-th cw-1-5">Data inizio</div>
                            <div class="block-data-table-th cw-1-5">Targa</div>
                            <div class="block-data-table-th cw-1-5">Durata (min)</div>
                            <div class="block-data-table-th cw-1-5">Sosta (min)</div>
                            <div class="block-data-table-th cw-1-5">Totale (&euro;)</div>
                        </div>
                        <!-- trip table headers -->

                        <!-- Trip table body -->
                        <div>
                            <div class="block-data-table-row clearfix odd">
                                <div class="block-data-table-td cw-1-5 table-row-fix"><?= $tripPayment->getTrip()->getTimestampBeginning()->format("Y-m-d H:i:s") ?></div>
                                <div class="block-data-table-td cw-1-5 table-row-fix"><?= $tripPayment->getTrip()->getCar()->getPlate() ?></div>
                                <div class="block-data-table-td cw-1-5 table-row-fix"><?= $tripPayment->getTripMinutes() ?></div>
                                <div class="block-data-table-td cw-1-5 table-row-fix"><?= $tripPayment->getParkingMinutes() ?></div>
                                <div class="block-data-table-td cw-1-5 table-row-fix"><?= number_format($tripPayment->getTotalCost() / 100, 2, ',', ' ') ?></div>
                            </div>
                        </div>
                        <!-- trip table body -->

                    </div>
                    <!-- trip table -->

                    <!-- Confirm button -->
                    <div class="block-wrapper-button content-align-center margin-top-custom">
                        <a href="<?= $this->url('cartasi/primo-pagamento-corsa') ?>"><button><?= $this->translate("Effettua pagamento"); ?></button></a>
                    </div>
                    <!-- confirm button -->

                        <?php
                            // if customer has no credit card and no trips
                            } else {
                        ?>

                    <h2>Non hai ancora consumato i minuti bonus</h2>

                    <?php
                        // close no credit card if
                        }
                    ?>

                    <?php
                        // if customer has credit card
                        } else {
                    ?>

                    <h2>Carta di credito registrata con successo!</h2>

                    <?php
                        // close has credit card if
                        }
                    ?>

                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
