<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', ['route' => 'dati-pagamento']); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Dati pagamento'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-3  clearfix">

                        <?php if($this->customer->getFirstPaymentCompleted()): ?>

                            <?php //if (!$this->cartasiCompletedFirstPayment): ?>

                                <!--div class="block-alert margin-bottom info">
                                    <p><? //echo $this->translate('Il primo pagamento è stato effettuato. Per abilitare i pagamenti ricorrenti è necessario registrare la proprio carta nel circuito Cartasi effettuando un pagamento iniziale di 10 €.') ?></p>
                                    <a href="<? //echo $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]) ?>">
                                        <button class="medium red"><? //echo $this->translate("Clicca qui"); ?></button>
                                    </a> <?= $this->translate("per completare l'attivazione del servizio"); ?>.</p>
                                </div-->

                            <? //php else: ?>

                                <div class="block-alert margin-bottom info">
                                    <p>
                                        <?= $this->translate('Il pagamento della quota di iscrizione è andato a buon fine, grazie'); ?>.
                                    </p>
                                </div>

                            <?php // endif; ?>

                        <?php else: ?>
                            <div class="block-alert margin-bottom info">
                                <p><?= $this->translate('La quota di iscrizione non risulta ancora pagata'); ?>. <a href="<?= $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]) ?>"><button class="medium red"><?= $this->translate("Clicca qui"); ?></button></a> <?= $this->translate("per completare l'attivazione del servizio"); ?>.</p>
                            </div>
                        <?php endif; ?>
                    </div>
                    <!-- block-form -->

                    <!-- block -->
                    <div class="bw-f w-1-3 last  clearfix">

                    </div>
                    <!-- block -->

                </div>
                <!-- module-manage-card -->

            </div>
            <!-- module-column-app-content -->

        <?php
        // if necessary create link to the activation page
            if ($this->activateLink) {
        ?>
            <div class="module-column-app-content clearfix">

                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">

                    <p>Hai esaurito i tuoi minuti bonus e hai effettuato una o più corse "a debito". Puoi effettuare manualmente il primo pagamento cliccando sul seguente link.</p>
                    <!-- Activation button -->
                    <div class="block-wrapper-button content-align-center margin-top-custom">
                        <a href="<?= $this->url('area-utente/activate-payments') ?>"><button><?= $this->translate("Maggiori informazioni"); ?></button></a>
                    </div>
                    <!-- activation button -->

                </div>
            </div>
        <?php
            }
        ?>

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
