<?php
$form = $this->driverLicenseForm->prepare();
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'));
?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', ['route' => 'patente']); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('PATENTE'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-manage-driver-license -->
                <div class="module-manage-driver-license padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-car"></i> <?= $this->translate('I dati della tua patente'); ?></h2>
                        </div>

                        <div id="viewDriverLicense">
                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Numero patente'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type="text" class="required disabled" name="" value="<?= $this->customer->getDriverLicense(); ?>" >
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata da autorit&agrave;'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseAuthority = $form->get('driver')->get('driverLicenseAuthority');
                                        echo $this->formElement($driverLicenseAuthority->setAttribute('class', 'disabled'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Conseguita il'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type="text" class="required disabled" name="" value="<?= $this->customer->getDriverLicenseReleaseDate()->format('d-m-Y'); ?>" >
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Data di scadenza'); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getDriverLicenseExpire()->format('d-m-Y'); ?>" >
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Nome sulla patente'); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getDriverLicenseName(); ?>" >
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Cognome sulla patente'); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getDriverLicenseSurname(); ?>" >
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label style="margin-right: 5px;"><?= $this->translate('Patente estera?'); ?></label>
                                        <?php
                                        $driverLicenseForeign = $form->get('driver')->get('driverLicenseForeign');
                                        echo $this->formElement($driverLicenseForeign->setAttribute('class', 'disabled'));
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata (nazione)'); ?></label>
                                        <?php
                                        $driverLicenseCountry= $form->get('driver')->get('driverLicenseCountry');
                                        echo $this->formElement($driverLicenseCountry->setAttribute('class', 'disabled'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-form-section content-align-center margin-bottom">
                                <h2><i class="fa fa-folder-open"></i> <?= $this->translate('Categoria patente'); ?></h2>
                            </div>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field content-align-center bw-f w-4-4">
                                    <p>
                                        <?php
                                        $value = str_replace("{","", $this->customer->getDriverLicenseCategories());
                                        $value = str_replace("}","",$value);
                                        $driverLicense = explode(',', $value);
                                        $driverLicenseCategories = $form->get('driver')->get('driverLicenseCategories');
                                        foreach ($driverLicenseCategories->getValueOptions() as $key => $value): ?>
                                            <?php echo $key; ?>
                                            <input type='checkbox' class="disabled" name="<?php echo $driverLicenseCategories->getName() ?>[]" value="<?php echo $value; ?>" <?= in_array($key, $driverLicense) ? 'checked' : ''; ?>>
                                        <?php endforeach; ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button id="js-edit" type="button"><?= $this->translate('Modifica'); ?></button>
                            </div>
                        </div>

                        <div id="editDriverLicense" style="display: none;">

                            <?= $this->form()->openTag($form); ?>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Numero patente'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicense = $form->get('driver')->get('driverLicense');
                                        echo $this->formElement($driverLicense);
                                        echo $this->formElementErrors($driverLicense, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata da autorit&agrave;'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseAuthority = $form->get('driver')->get('driverLicenseAuthority');
                                        echo $this->formElement($driverLicenseAuthority->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($driverLicenseAuthority, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Conseguita il'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseReleaseDate = $form->get('driver')->get('driverLicenseReleaseDate');
                                        echo $this->formElement($driverLicenseReleaseDate);
                                        echo $this->formElementErrors($driverLicenseReleaseDate, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Data di scadenza'); ?></label>
                                        <?php
                                        $driverLicenseExpire = $form->get('driver')->get('driverLicenseExpire');
                                        echo $this->formElement($driverLicenseExpire);
                                        echo $this->formElementErrors($driverLicenseExpire, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Nome sulla patente'); ?></label>
                                        <?php
                                        $driverLicenseName = $form->get('driver')->get('driverLicenseName');
                                        echo $this->formElement($driverLicenseName);
                                        echo $this->formElementErrors($driverLicenseName, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Cognome sulla patente'); ?></label>
                                        <?php
                                        $driverLicenseSurname = $form->get('driver')->get('driverLicenseSurname');
                                        echo $this->formElement($driverLicenseSurname);
                                        echo $this->formElementErrors($driverLicenseSurname, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label style="margin-right: 5px;"><?= $this->translate('Patente estera?'); ?></label>
                                        <?php
                                        $driverLicenseForeign = $form->get('driver')->get('driverLicenseForeign');
                                        echo $this->formElement($driverLicenseForeign->setAttribute('class', 'enabled'));
                                        echo $this->formElementErrors($driverLicenseForeign, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata (nazione)'); ?></label>
                                        <?php
                                        $driverLicenseCountry= $form->get('driver')->get('driverLicenseCountry');
                                        echo $this->formElement($driverLicenseCountry->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($driverLicenseCountry, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-form-section content-align-center margin-bottom">
                                <h2><i class="fa fa-folder-open"></i> <?= $this->translate('Categoria patente'); ?></h2>
                            </div>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field content-align-center bw-f w-4-4">
                                    <p>
                                        <?php
                                        $value = str_replace("{","", $this->customer->getDriverLicenseCategories());
                                        $value = str_replace("}","",$value);
                                        $driverLicense = explode(',', $value);
                                        $driverLicenseCategories = $form->get('driver')->get('driverLicenseCategories');
                                        foreach ($driverLicenseCategories->getValueOptions() as $key => $value): ?>
                                            <label class='control checkbox checkbox--patente'>
                                                <input type='checkbox' name="<?php echo $driverLicenseCategories->getName() ?>[]" value="<?php echo $value; ?>" <?= !is_null($driverLicenseCategories->getValue()) && in_array($value, $driverLicense) ? 'checked' : '' ?>>
                                                <span class='control-indicator'><?php echo $key; ?></span>
                                            </label>
                                        <?php endforeach; ?>
                                        <?php echo $this->formElementErrors($driverLicenseCategories, ['class' => 'errors']); ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button class="reset" id="js-reset" type="button"><?= $this->translate('Annulla'); ?></button>
                                <button type="submit"><?= $this->translate('Salva modifiche'); ?></button>
                            </div>

                            <?php echo $this->form()->closeTag(); ?>
                        </div>

                    </div>
                    <!-- block-form -->

                    <!-- block -->
                    <div class="bw-f w-1-3 last  clearfix">
                        <?php if ($this->driversLicenseUpload): ?>
                            <div class="block-form bw-f w-4-4  clearfix">

                                <div class="block-form-section content-align-center margin-bottom">
                                    <h2><?= $this->translate("Abilitazione patente"); ?></h2>
                                </div>

                                <div class="block-alert info margin-bottom right">
                                    <p>Per verificare la validità della tua patente estera, è necessario caricare una copia della propria patente. Puoi procedere subito, cliccando il bottone sottostante. Finchè la validità della tua patente non sarà verificata, non potrai utilizzare il servizio di SHARE’NGO.</p>
                                </div>

                                <div class="block-wrapper-button content-align-center">
                                    <a href="<?= $this->url('foreign-drivers-license', ['hash' => $this->customer->getHash()]) ?>" target="_blank"><button type="button"><?= $this->translate('Procedi'); ?></button></a>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <!-- block -->
                </div>
                <!-- module-manage-driver-license -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->


<!-- module-modal -->
<div class="module-modal" style="height:2400px; display: none;">
    <!-- modal-overlay -->
    <div class="modal-overlay">
        <!-- module-pop-up -->
        <div class="module-pop-up" style="margin:180px auto;">

            <a class="btn-close"><i class="fa fa-close"></i></a>

            <!-- module-pop-up-content -->
            <div class="module-pop-up-content">

                <!-- block-pop-up-generic-content -->
                <div class="block-pop-up-generic-content">
                    <img src="<?= $this->basePath('images/patente-fac-simile.jpg'); ?>" alt="">
                    <p>
                        <?= $this->translate('5. Numero Patente<br>4. Data di rilascio<br>4c. Autorit&agrave; di rilascio<br>'); ?>
                    </p>
                </div>
                <!-- block-pop-up-generic-content -->

            </div>
            <!-- module-pop-up-content -->

        </div>
        <!-- module-pop-up -->
    </div>
    <!-- modal-overlay -->
</div>
<!-- module-modal -->

<?php
if($this->showError) {
    $this->inlineScript()->captureStart();

    echo <<<JS
    $(document).ready(function() {
        $('#viewDriverLicense, #editDriverLicense').toggle();
    });
JS;
    $this->inlineScript()->captureEnd();
}
?>
<?php $this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function() {

        $('.btn-close, .fa-info-circle').click(function (e) {
            e.preventDefault();
            $('.module-modal').toggle();
        });

        $("#driverLicenseReleaseDate" ).datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0",
            maxDate: new Date(new Date().getFullYear(), 11, 31)
        });

         $("#driverLicenseExpire" ).datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "+0:+100",
            minDate: new Date(new Date().getFullYear(), 0, 1)
        });

        $("#js-edit, #js-reset").click(function() {
            $("#viewDriverLicense, #editDriverLicense").toggle();
        });
    });
JS;
$this->inlineScript()->captureEnd(); ?>

