<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- module-list-archive -->
        <section class="module-list-archive margin-top">
            
            <h1 class="module-main-title"><?php echo $this->translate('Pagina non trovata') ?></h1>
            
            <h2><?php echo $this->translate('La pagina richiesta non è stata trovata.')?></h2>

        </section>

    </div>

</div>