<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <div class="block-form-section content-align-center margin-bottom">
                <h2><i class="fa fa-thumbs-up"></i> <?= $this->translate('Validazione patente') ?></h2>
            </div>

            <div class="margin-bottom">
                <h1><?= $this->translate('Procedura completata')?></h1>
                <br>
                <p><?= $this->translate('La verifica della tua patente è in corso. Quando avremo verificato la validità della tua patente, potrai iniziare ad utilizzare i servizi di SHAREN`GO.') ?></p>
            </div>
        </div>
    </div>
</div>
