<ul>
    <!--li><a href=""><i class="fa fa-crosshairs"></i> <?= $this->translate('Noleggia auto'); ?></a></li-->
    <li>
        <a href="<?= $this->url('area-utente'); ?>" <?= $this->route === 'profile' ? 'class="active"' : '' ?>>
            <i class="fa fa-user"></i>
            <?= $this->translate('Profilo'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/rents'); ?>" <?= $this->route === 'rents' ? 'class="active"' : '' ?>>
            <i class="icon icon-car-small-fff"></i> <?= $this->translate('Le mie corse'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/tariffe'); ?>" <?= $this->route === 'tariffe' ? 'class="active"' : '' ?>>
            <i class="fa fa-money"></i>
            <?= $this->translate('Tariffe'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/pin'); ?>" <?= $this->route === 'pin' ? 'class="active"' : '' ?>>
            <i class="fa fa-lock"></i>
            <?= $this->translate('PIN'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/invoices-list'); ?>" <?= $this->route === 'invoices-list' ? 'class="active"' : '' ?>>
        <i class="fa fa-file-o"></i> <?= $this->translate('Fatture'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/dati-pagamento'); ?>" <?= $this->route === 'dati-pagamento' ? 'class="active"' : '' ?>>
            <i class="fa fa-credit-card"></i>
            <?= $this->translate('Dati di pagamento'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/bonus'); ?>" <?= $this->route === 'bonus' ? 'class="active"' : '' ?>>
            <i class="fa fa-trophy"></i>
            <?= $this->translate('Bonus'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/additional-services'); ?>" <?= $this->route === 'additional-services' ? 'class="active"' : '' ?>>
            <i class="fa fa-plus"></i>
            <?= $this->translate('Servizi aggiuntivi'); ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('area-utente/patente'); ?>" <?= $this->route === 'patente' ? 'class="active"' : '' ?>>
        <i class="fa fa-tachometer"></i> <?= $this->translate('Patente'); ?>
        </a>
    </li>
    <!--li><a href=""><i class="fa fa-trophy"></i> <?= $this->translate('Bonus'); ?></a></li>
    <li><a href=""><i class="fa fa-file-o"></i> <?= $this->translate('Fatture'); ?></a></li>
    <li><a href=""><i class="fa fa-tachometer"></i> <?= $this->translate('Patente'); ?></a></li>
    <li><a href=""><i class="fa fa-plus"></i> <?= $this->translate('Servizi aggiuntivi'); ?></a></li>
    <li><a href=""><i class="fa fa-map-marker"></i> <?= $this->translate('Posiziona auto'); ?></a></li-->
</ul>
