<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', ['route' => 'additional-services']); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('servizi aggiuntivi'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <!-- Promo code section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-4-4">
                                    <p> <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                        $promoCode = $form->get('promocode')->get('promocode');
                                        echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($promoCode, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type=submit name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->

                    <!-- Margin -->
                    <div class="block-form bw-f margin-separator"></div>

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista Pacchetti'); ?></h2>
                        </div>
                        <!-- title -->

                        <!-- Description -->
                        <div class="content-align-center block-title highlight">
                            <?= $this->translate('TIPO CHE SEI, PACCHETTO CHE TROVI') ?>
                        </div>
                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title">
                                <?= $this->translate('Scegli il pacchetto minuti che preferisci e il costo dei tuoi noleggi SHARE’N GO
                                scende fino ad arrivare a 6 € l’ora, la tariffa di car sharing a flusso libero
                                più bassa al mondo. Più ti muovi e più scopri quanto piacevole e conveniente
                                sia la mobilità elettrica e condivisa.') ?>
                            </span>
                        </div>
                        <br><br>
                        <!-- packages -->
                        <div class="block-data-table clearboth clearfix">
                        <?php
                            foreach ($bonusPackages as $package) {
                        ?>
                            <div class="bw-f w-1-4 clearfix">
                                <div class="bw-f w-1-2 clearfix">
                                    <img style="width:110px;" src="<?= $this->basePath('images/pacco_regalo.png') ?>" alt="">
                                </div>
                                <div class="bw-f w-1-2 clearfix">
                                    <div class="content-align-center">
                                        <p class="fa-2x highlight font-weight bold"><?= strtoupper($this->translate($package->getName())) ?></p>
                                        <p class="block-sub-title"><?= $package->getMinutes() ?> <?= $this->translate('min') ?> <?= $this->translate('a') ?> <?= sprintf("%.0f &euro;", $package->getCost() / 100) ?></p>
                                        <p class="block-sub-title">(<?= sprintf("%.2f &euro;", ($package->getCost() / 100) / $package->getMinutes()) ?>/<?= $this->translate('min') ?>)</p>
                                        <p class="block-sub-title"><?= $this->translate('Validità') ?>
                                            <?php
                                                // Duration is expressed in 30-days multiplies (ex. 30, 60, 90 etc...)
                                                $months = floor($package->getDuration() / 30);
                                                echo ' '.$months.' '.($months > 1 ? $this->translate('mesi') : $this->translate('mese'));
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php
                            // end foreach
                            }
                        ?>
                        </div>
                        <!-- packages -->

                        <!-- description -->
                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Minuti'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Prezzo'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido dal'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Disponibile fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Acquista'); ?></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                    $i++;
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getMinutes() . (" min.") ?></div>
                                <div class="block-data-table-td cw-1-7"><?= sprintf("%.2f &euro;", $package->getCost() / 100) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->validFromOrToday()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7"><?= sprintf($this->translate("per %d gg"), $package->getDuration()); ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getBuyableUntil()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7">
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->

                            <?php
                                // end foreach
                                }
                            ?>

                        </div>
                        <!-- table -->

                    </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="bw-f w-1-3 last clearfix"></div>
                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }

    .errors li {
        color: red;
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
?>
