<div id="main">

<!-- module-wizard -->
<div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

<!-- block-form -->
<div class="block-form w-3-4 auto-margin clearfix">

    <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i> Grazie per la tua registrazione a Share'ngo con Facebook</h2>
    </div>

    <div class="margin-bottom">
        <p>Ti abbiamo mandato una mail, dove trovi il link per completare con comodo la tua iscrizione <span style="color: red;">(attenzione, guarda anche nella cartella SPAM).</span></p>

        <p>Se puoi iscriverti ora, clicca qui: <a href="<?= $this->url('signup') ?>"><?= $this->url('signup', [], ['force_canonical' => true]) ?></a>. Grazie!</p>
    </div>

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
<!-- main -->