<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Login'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <?php
        $form = $this->forgotForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('forgot'));
        $form->setAttribute('method', 'post');
        ?>

        <?php echo $this->form()->openTag($form) ?>
            <!-- block-form -->
            <div class="block-form w-2-4 auto-margin clearfix">

                <div class="block-form-section content-align-center margin-bottom">
                    <h2><i class="fa fa-repeat"></i> <?= $this->translate('Recupera la password'); ?></h2>
                </div>

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-4-4">
                        <p> <label><?= $this->translate('Email'); ?></label>
                            <?php
                            $email = $form->get('email');
                            echo $this->formElement($email->setAttributes(['class' => 'required', 'placeholder' => $this->translate('Inserisci la tua email')]));
                            ?>
                        </p>
                    </div>
                </div>
                <!-- block-row-field -->

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-4-4">
                        <p>
                            <?= $this->translate('Inserisci il tuo indirizzo email e invia la richiesta per reimpostare la password.'); ?>
                            <br><?= $this->translate('DOPO AVER INVIATO LA RICHIESTA CONTROLLA LA TUA EMAIL E SEGUI IL LINK PER CAMBIARE LA PASSWORD'); ?>
                        </p>
                    </div>

                </div>
                <!-- block-row-field -->

                <div class="block-wrapper-button content-align-center">
                    <input type="submit" name="" value="<?= $this->translate('Procedi'); ?>">
                </div>
            </div>
            <!-- block-form -->
        <?php echo $this->form()->closeTag() ?>
    </div>
    <!-- content -->
</div>
<!-- main -->
