<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Recupero Password'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">
    <!-- content -->
    <div class="content">
        <div class="block-form w-2-4 auto-margin clearfix">
            <div class="block-form-section content-align-center margin-bottom">
                <h1><?php echo $this->translate('La tua password è stata cambiata.'); ?></h1>
                <p><?php echo $this->translate('Adesso puoi loggarti usando la tua nuova password.') ?></p>
            </div>
        </div>
    </div>
    <!-- content -->
</div>
<!-- main -->