<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Recupero password'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">
    <!-- content -->
    <div class="content">
        <div class="block-form w-2-4 auto-margin clearfix">
            <div class="block-form-section content-align-center margin-bottom">
                <h5><?php echo sprintf($this->translate('Controlla l\'email che ti abbiamo spedito al tuo indirizzo %s.'), $this->escapeHtml($this->email)); ?></h5>
            </div>
        </div>
    </div>
    <!-- content -->
</div>
<!-- main -->