<?php

$this->placeholder('google-track-adwords')->set('<!-- Google Code for Preventivo Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 953520877;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "wYOdCOz65lwQ7aXWxgM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/953520877/?label=wYOdCOz65lwQ7aXWxgM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
');

?>
<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

 <!-- module-wizard -->
 <div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

    <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i> <?= $this->translate('Registrazione completata con successo!'); ?></h2>
    </div>

    <!-- block-alert -->
    <div class="block-alert margin-bottom right">
        <h2 class="block-title"><i class="fa fa-check-circle"></i> <?= $this->translate('Attivazione account'); ?></h2>
        <p>
            <?= $this->translate('Controlla nella tua casella di posta e clicca sul link suggerito dalla mail inviata per ATTIVARE l\'account.'); ?>
        </p>
    </div>
    <!-- block-alert -->

    <!--div class="content-align-center margin-bottom">
        Le app per smartphone saranno disponibili da metà Giugno, prima in versione HTML e successivamente in versione nativa.
        Continua a controllare il sito per sapere quando sarà disponibile
    </div-->

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
               <!-- main -->