<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

 <!-- module-wizard -->
 <div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

     <div class="margin-bottom" style="text-align: center;">
        <h1><?= $this->translate('Attivazione completata')?></h1>
     </div>

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
               <!-- main -->