<!-- Facebook Conversion Code for registration Florence -->
<?php
$this->placeholder('facebook-pixel')->set('
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');

fbq(\'init\', \'423565347840059\');
fbq(\'track\', "PageView");
fbq(\'track\', \'CompleteRegistration\');</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=423565347840059&ev=PageView&noscript=1"
/></noscript>
');
?>

<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

<!-- module-wizard -->
<div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

<!-- block-form -->
<div class="block-form w-3-4 auto-margin clearfix">

    <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i> <?= $this->message ?></h2>
    </div>

    <?php if ($this->enable_payment) { ?>
     <!--div class="margin-bottom">
        <h1><? //= $this->translate('Completa l\'attivazione del servizio')?></h1>
        <p><? //= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento di 10&euro; via PayPal.')?></p>
     </div>


     <!--div class="module-wrapper-button margin-bottom content-align-center">
         <a href="<? //$this->url('pay', ['email' => $this->email]) ?>" class="btn-link x-large ct2"><? //= $this->translate('Esegui il pagamento di 10€'); ?> <i class="fa fa-plus-circle"></i></a>
     </div-->

    <!--div class="block-form-section content-align-center">
        <h2><? //= $this->translate('GRAZIE'); ?></h2>
        <div style="color: black; line-height: 1.5; margin-bottom: 30px;"><? //= $this->translate('Qualche giorno prima dell’attivazione del servizio a Milano, prevista per lunedi 15 giugno, ti verrà richiesto di completare la tua iscrizione con il pagamento dei 10€ che comprende i primi 500 minuti di utilizzazione dell’Equomobile.'); ?></div>
        <div style="color: black; line-height: 1.5; font-size: 1em;"><? //= $this->translate('Il mancato pagamento dell’iscrizione entro il 14 giugno a mezzanotte comporterà la perdita del diritto che hai maturato ai 500 minuti gratuiti previsti con la promozione di lancio di SHARE’NGO'); ?></div>
    </div-->

    <div class="margin-bottom">
        <h1><?= $this->translate('Completa l\'attivazione del servizio')?></h1>
        <?php if ($this->benefitsFromDiscountedSubscriptionAmount) { ?>
            <p><?= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento di ' . $this->subscriptionDiscountedAmount . '&euro; via Cartasi.')?></p>
        <?php } else { ?>
            <p><?= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento via Cartasi.')?></p>
        <?php } ?>
        <p><?= $this->translate('Controlla nelle tue mail se la verifica della tua patente ha dato esito positivo,<br>se così non fosse accedi alla tua riservata e verifica i tuoi dati prima di effettuare il pagamento.<br>In caso di patente straniera il servizio clienti la validerá una volta fatte le opportune verifiche.')?></p>
    </div>

    <div class="module-wrapper-button margin-bottom content-align-center">
        <a href="<?= $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customerId]]) ?>" class="btn-link x-large ct2"><?= $this->translate('Esegui il pagamento'); ?> <i class="fa fa-plus-circle"></i></a>
    </div>

    <?php } ?>

    <?php if ($this->needsDriversLicenseUpload): ?>
        <div class="block-alert info margin-bottom right">
            <h2 class="block-title"></i><?= $this->translate('Abilitazione patente'); ?></h2>
            <p>
                <?= $this->translate('Per verificare la validità della tua patente estera, è necessario caricare una copia della propria patente. Puoi procedere subito, '); ?>
                <a href="<?= $this->url('foreign-drivers-license', ['hash' => $this->hash]) ?>" target="_blank"><?= $this->translate('qui') ?></a>
                <?= $this->translate(', oppure farlo in secondo momento dalla tua area riservata. Finchè la validità della tua patente non sarà verificata, non potrai utilizzare il servizio di SHARE’NGO.')?>
            </p>
        </div>
    <? endif; ?>

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
<!-- main -->
