<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

            <h1 class="block-title"><?= $this->translate('Come funziona'); ?></h1>

            <br>
            <h2><?= $this->translate('Iscrizione a Share’ngo'); ?></h2>
            <p><?= $this->translate('Se hai più di 18 anni, puoi iscriverti a Share’ngo in pochi minuti direttamente dalla pagina '); ?><a href="<?= $this->url('signup'); ?>">www.sharengo.it/signup</a><?= $this->translate('. Tieni a portata di mano la patente, il codice fiscale e la carta di credito, anche prepagata. L\'iscrizione a Share’ngo costa 10 euro e comprende i primi 30 minuti di guida gratuita e la Share’ngo Card (per aprire l’auto anche senza smartphone).'); ?></p>

            <h2><?= $this->translate('Quanto costa? Poco, meno della tua auto privata'); ?></h2>
            <p><?= $this->translate('La tariffa base è 0,28 € al minuto e quella di sosta è 0,10 € al minuto. Ma se credi nella mobilità urbana elettrica puoi spendere molto meno e scoprire in un attimo perché Share’ngo è di gran lunga il servizio di car sharing più conveniente della tua città. '); ?></p>

            <p style='margin-left:20pt;text-indent:-18.0pt'><span style='font-size:12.0pt;font-family:Symbol'>·&nbsp;&nbsp;&nbsp;</span>
            <b><span style='color:green'><?= $this->translate('PUOI AVERE UNA TARIFFA PERSONALIZZATA.'); ?> </span></b>
            <?= $this->translate('Se non hai utilizzato un Codice Promo in fase di iscrizione, puoi ottenere uno sconto e avere un Piano Tariffario Personale, perché noi riconosciamo il tuo bisogno di mobilità e premiamo la tua partecipazione alla sharing economy. Una volta registrato al servizio basterà accedere al tuo Profilo Personale (sul sito o nella nostra App), andare nella sezione “Tariffe”, cliccare sul banner che ti offre lo sconto e rispondere ad alcune domande per bloccare lo'); ?>
            <i>&nbsp;<?= $this->translate('sconto che ti spetta'); ?>&nbsp;</i>
            <?= $this->translate('per un anno.'); ?></p>

            <p style='margin-left:20pt;text-indent:-18.0pt'><span style='font-size:12.0pt;font-family:Symbol'>·&nbsp;&nbsp;&nbsp;</span>
            <b><span style='color:green'><?= $this->translate('PUOI ACQUISTARE I PACCHETTI MINUTI. Sono disponibili nei tagli da 100/200/500 e 1000 minuti'); ?> </span></b>
            <?= $this->translate('e ti permettono di ridurre molto il costo dei tuoi noleggi, fino a 0,10 € al minuto o 6 €/ora, il costo più basso al mondo per un servizio di car sharing a flusso libero.'); ?></p>

            <p style='margin-bottom:3pt!important'><b><?= $this->translate('E la convenienza di Share’ngo non finisce qui!'); ?></b></p>
            <p style='margin-left:40pt;text-indent:-18.0pt;margin-bottom:3pt!important'><span style='font-size:12.0pt;font-family:Symbol'>·&nbsp;&nbsp;&nbsp;</span>
            <?= $this->translate('il chilometraggio per singola corsa è illimitato (senza extra, a differenza degli altri car sharing)'); ?></p>
            <p style='margin-left:40pt;text-indent:-18.0pt;margin-bottom:3pt!important'><span style='font-size:12.0pt;font-family:Symbol'>·&nbsp;&nbsp;&nbsp;</span>
            <?= $this->translate('per le donne le corse notturne sono gratuite dall’1 alle 6!'); ?></p>
            <p style='margin-left:40pt;text-indent:-18.0pt'><span style='font-size:12.0pt;font-family:Symbol'>·&nbsp;&nbsp;&nbsp;</span>
            <?= $this->translate('il giorno del tuo compleanno ricevi 30 minuti bonus'); ?>.</p>
            
            <p><?= $this->translate('L’iscrizione, le corse  e i pacchetti minuti di Share’ngo sono pagabili con carta di credito, anche prepagata o ricaricabile. Nella pagina del tuo Profilo Personale troverai sempre tutte le corse che hai effettuato, il loro costo e potrai scaricare le tue fatture.'); ?></p>

            <h2><?= $this->translate('Trovare e prenotare un’auto quando e dove ti serve'); ?></h2>
            <p><?= $this->translate('Una volta scaricata la nostra App per'); ?>&nbsp;<a href="https://itunes.apple.com/it/app/sharengo-cs/id1093104891?l=en&mt=8">iOS</a>&nbsp;<?= $this->translate('e') ?>&nbsp;<a href="https://play.google.com/store/apps/details?id=it.sharengo.eteria">Android</a>&nbsp;<?= $this->translate('- o fatto il login su'); ?>&nbsp;<a href="http://mobile.sharengo.it">mobile.sharengo.it</a>&nbsp;<?= $this->translate('- è facilissimo prenotare un’auto di Share’ngo. Vai sulla mappa della tua città e vedi tutte le auto disponibili, con la loro autonomia. Quando hai trovato l’auto più vicina, clicca su “Prenotala ora”. La prenotazione è gratuita e dura 30 minuti.'); ?></p>

            <h2><?= $this->translate('Un\'auto semplice e molto divertente da guidare'); ?></h2>
            <p><?= $this->translate('Guidare un’auto elettrica di Share’ngo è molto facile e divertente. In prossimità dell\'auto prenotata, con un clic sul tuo smartphone apri le portiere (puoi anche aprirle passando la tua Share’ngo Card sul lettore). Inserisci sul computer di bordo il tuo PIN (che trovi nella pagina del tuo Profilo Personale sul sito o sulla App) e gira la chiave: la tua macchina sarà “READY”, cioè pronta per muoversi. È un’auto molto semplice da guidare, con il cambio automatico e prestazioni che ti stupiranno: fino a 120 km di autonomia, 80 km/ora, la ripresa brillante di un’auto elettrica e il comfort a bordo di una citycar con sensori di parcheggio, luci a led, finestrini elettrici, radio e navigatore. Vuoi vedere nel dettaglio come funziona: leggi le'); ?>&nbsp;<a href="http://support.sharengo.it/come-guido-auto">FAQ&nbsp;<?= $this->translate('dedicate'); ?></a>!</p>

            <h2><?= $this->translate('Fine noleggio o sosta'); ?></h2>
            <p><?= $this->translate('Una corsa si termina cliccando sulla “P” nel display di bordo e scegliendo una delle due opzioni: “Termina il noleggio” oppure “Metti in sosta”. In entrambi i casi le porte si chiuderanno da sole in 40 secondi, senza che tu debba preoccuparti d’altro che girare la chiave per spegnere il quadro, chiudere le luci, alzare i finestrini e tirare il freno a mano prima di uscire dall’auto. La chiave non è estraibile e resta inserita nel cruscotto. Non devi preoccuparti neanche della ricarica: ci pensiamo noi!'); ?></p>

            <h2><?= $this->translate('Dove puoi andare'); ?></h2>
            <p><?= $this->translate('Share’ngo è operativa nelle città di Milano, Roma e Firenze. Per ogni città è definita un’area di copertura del servizio (area operativa): nei limiti di autonomia della macchina che hai noleggiato puoi andare dove vuoi e fare tutte le soste che credi ma non puoi chiudere la corsa fuori da essa. Puoi entrare gratuitamente nell’Area C a Milano e nelle ZTL a Roma e Firenze. Con le nostre auto ,non è possibile guidare invece in autostrada, nelle zone pedonali e nelle corsie preferenziali (riservate a taxi e mezzi pubblici). Puoi parcheggiare gratis negli spazi a pagamento (strisce blu) e in quelli riservati ai residenti (strisce gialle a Milano, strisce bianche a Firenze e a Roma). Non puoi invece parcheggiare nei posti riservati a taxi, mezzi pubblici, disabili, scarico merci ecc.'); ?></p>

            <h2><?= $this->translate('Le coperture assicurative'); ?></h2>
            <p><?= $this->translate('Sui nostri veicoli è garantita una copertura RC fino a 10.000.000 €. Le macchine sono coperte anche da polizza Kasko e assicurazione Furto e Incendio, atti vandalici ed eventi atmosferici (in entrambi i casi con franchigia di 500 €). Il conducente è assicurato per infortuni (PAI) per un massimale di 50.000 €.'); ?></p>

            <h2><?= $this->translate('Bambini a bordo'); ?></h2>
            <p><?= $this->translate('Le nostre auto sono dotate di cinture di sicurezza omologate e quindi non si applica l’articolo 172 del codice della strada che vieta il trasporto di minori di tre anni sui veicoli a motore che ne siano sprovvisti (serve ovviamente il seggiolino omologato). Non essendoci l’airbag, non si ci sono limitazioni per portare i minori sul sedile del passeggero, purché il seggiolino di sicurezza sia rivolto all’indietro.'); ?></p>

            <h2><?= $this->translate('Pagamenti e fatturazione del servizio'); ?></h2>
            <p><?= $this->translate('Le corse Share‘ngo sono pagabili con carta di credito, anche prepagata. Se non hai acquistato minuti di noleggio a pacchetto, a ogni singola corsa corrisponderà un addebito e una fattura scaricabile nel tuo Profilo Personale, dove potrai controllare le tue tariffe, quanti minuti gratuiti o pre-acquistati hai consumato e quanti te ne sono rimasti.'); ?></p>

            <h2><?= $this->translate('Contratto e regolamento'); ?></h2>
            <p><?= $this->translate('Il contratto con Share’go è disponibile a'); ?>&nbsp;<a href="http://www.sharengo.it/pdf/Contratto_Sharengo.pdf"><?= $this->translate('questa pagina'); ?></a>.&nbsp;<?= $this->translate('Se hai altre domande sul funzionamento del servizio, consulta le nostre'); ?>&nbsp;<a href="http://support.sharengo.it/home">FAQ</a>.</p>

            <h2><span style='color:green'><?= $this->translate('ISCRIVITI OGGI A SHARE’NGO E SCOPRI IL PIACERE DELLA MOBILITÀ ELETTRICA IN CITTÀ!') ?></span></h2>
            <br>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->