<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

            <h1 class="block-title"><?= $this->translate('Contatti / SOS'); ?></h1>
            <br>
            <h2><?= $this->translate('In caso di Incidente'); ?></h2>
            <p><?= $this->translate('Nel caso si verifichi un incidente (o un sinistro) che coinvolga altre persone, contatta immediatamente le Forze dell\'Ordine e, successivamente, il nostro servizio di assistenza.
            Inoltre ti verr&agrave chiesto di fornire tutti i dati utili (e necessari) alla ricostruzione della vicenda.'); ?></p>

            <h2><?= $this->translate('Assistenza Tecnica da veicolo'); ?></h2>
            <p><?= $this->translate('In caso di problemi con un mezzo Share’nGo &egrave; possibile inviare una richiesta al nostro centro assistenza premendo il pulsante SOS sul tablet di bordo.
            Verr&agrave richiesto l’inserimento di un numero di cellulare sul quale essere richiamati (se non ne &egrave stato inserito uno durante la registrazione o se differisce da quest’ultimo).'); ?></p>

            <h2><?= $this->translate('Per INFO'); ?></h2>
            <p><?= $this->translate('Se vuoi ricevere informazioni sul servizio Share\'nGo, puoi contattarci al numero '); ?><strong>0586 1975772</strong><?= $this->translate(' oppure all’indirizzo email '); ?><b><a href="mailto:servizioclienti@sharengo.eu">servizioclienti@sharengo.eu</a></b>.</p>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->