<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Login'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-form -->
        <div class="block-form w-2-4 auto-margin clearfix">

            <div class="block-form-section content-align-center margin-bottom">
                <h2><i class="fa fa-user"></i> <?= $this->translate("Accedi all'applicazione"); ?></h2>
            </div>

            <?php
            echo $this->flashMessenger()
                ->setMessageOpenFormat('<br><b>')
                ->setMessageCloseString('</b><br><br>')
                ->render();
            ?>

            <?php
            $form = $this->loginForm;
            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/login'));
            $form->setAttribute('method', 'post');
            ?>

            <?php echo $this->form()->openTag($form) ?>

                <!-- block-row-field -->
                <div class="block-row-field clearfix">
                    <div class="block-field bw-f w-4-4">
                        <?php echo $this->formElementErrors($form->get('identity'), ['class' => 'error-login']) ?>

                        <p> <label><?= $this->translate('Username'); ?></label>
                            <?php echo $this->formInput($form->get('identity')->setAttributes(['class' => 'required', 'placeholder' => $this->translate('La tua email')])); ?>
                        </p>
                    </div>
                </div>
                <!-- block-row-field -->

                <!-- block-row-field -->
                <div class="block-row-field clearfix">
                    <div class="block-field bw-f w-4-4">
                        <p> <label><?= $this->translate('Password'); ?></label>
                            <?php echo $this->formInput($form->get('credential')->setAttribute('class', 'required')) ?>
                        </p>
                    </div>
                </div>
                <!-- block-row-field -->

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-2-4">
                        <p>
                            <!--<input type="checkbox" name="" value=""> <?/* $this->translate('ricordami'); */?><br>-->
                            <a href="<?= $this->url('forgot'); ?>"> <?= $this->translate('Password dimenticata ?'); ?></a>
                        </p>
                    </div>
                    <div class="block-field content-align-right bw-f w-2-4">
                        <p><input type="submit" name="" value="<?= $this->translate('Accedi'); ?>"></p>
                    </div>
                </div>
                <!-- block-row-field -->

            <?php echo $this->form()->closeTag() ?>
        </div>
        <!-- block-form -->
    </div>
    <!-- content -->
</div>
<!-- main -->
<?php $this->headStyle()->captureStart() ?>
.error-login {
    list-style-type: none;
}
.error-login li {
    color: red;
}
<?php $this->headStyle()->captureEnd() ?>
