<?php

return [
    'carrefour' => [
        'shops' => [
            '0102' => ['VIA TESSA (MI)','MILANO'],
            '0111' => ['CONCA S. NAVIGLIO (MI)','MILANO'],
            '0129' => ['VIA AMPERE (MI)','MILANO'],
            '0178' => ['VIA SETTEMBRINI (MI)','MILANO'],
            '0248' => ['NICOTERA','ROMA'],
            '0301' => ['SAN MARCO (MI)','MILANO'],
            '0406' => ['MICASTALDI','MILANO'],
            '0442' => ['GRAN SASSO (MI)','MILANO'],
            '0578' => ['STAZIONE PRENESTINA','ROMA'],
            '0588' => ['BOTERO','ROMA'],
            '0592' => ['CONIFERE','ROMA'],
            '0738' => ['RM IRNERIO','ROMA'],
            '0739' => ['RM DEMOCRITO','ROMA'],
            '0775' => ['RM ORTIFARNESI','ROMA'],
            '0776' => ['RM ARISTONICO','ROMA'],
            '0786' => ['RM FIDENZA','ROMA'],
            '0791' => ['RM VITTORIA','ROMA'],
            '0931' => ['RMGOVERNOVECCH','ROMA'],
            '1015' => ['SCALABRINI','MILANO'],
            '1181' => ['SARPI','MILANO'],
            '1336' => ['ROMANO','MILANO'],
            '1398' => ['MDARWIN','MILANO'],
            '1465' => ['PROCIDA','MILANO'],
            '1632' => ['MICUCCHIARI','MILANO'],
            '1633' => ['MIABRUZZI','MILANO'],
            '1634' => ['MIGARIAN','MILANO'],
            '1636' => ['MIGROSSICH','MILANO'],
            '1637' => ['MIMOSCOVA','MILANO'],
            '1638' => ['MIPARAVIA','MILANO'],
            '1639' => ['MIBEZZECCA','MILANO'],
            '1640' => ['MICASATI','MILANO'],
            '1641' => ['MIINAMA','MILANO'],
            '1643' => ['MIMAGISTRETTI','MILANO'],
            '1644' => ['MICERMENATE','MILANO'],
            '1645' => ['MIOGLIO','MILANO'],
            '1646' => ['MIEDOLO','MILANO'],
            '1690' => ['MIVENINI','MILANO'],
            '1691' => ['MIVERCELLI','MILANO'],
            '1692' => ['MITEANO','MILANO'],
            '1693' => ['MIVOLTRI','MILANO'],
            '1694' => ['MISENATORE','MILANO'],
            '1696' => ['MIGIANELLA','MILANO'],
            '1697' => ['MILAMBERTENGHI','MILANO'],
            '1698' => ['MISISMONDI','MILANO'],
            '1700' => ['MITRANSITI','MILANO'],
            '1702' => ['MIDOLCI','MILANO'],
            '1703' => ['MIPORVIGENTINA','MILANO'],
            '1713' => ['MIOLGETTINA','MILANO'],
            '1720' => ['MI VIGEVANO','MILANO'],
            '1979' => ['MIPIERLOMBARDO','MILANO'],
            '2065' => ['RMVCESAREPAVESE','ROMA'],
            '2096' => ['RMGROTTAPERFETTA','ROMA'],
            '2228' => ['ROMAVIAMENGARINI','ROMA'],
            '2229' => ['ROMASSQUATTRO','ROMA'],
            '2232' => ['ROMAVIAAPPIANO','ROMA'],
            '2233' => ['ROMACSOVITTORIO','ROMA'],
            '2388' => ['RM VIAMONTEGALLO','ROMA'],
            '2389' => ['RM VIA VENIERO','ROMA'],
            '2537' => ['ROMA VIA TAVOLACCI','ROMA'],
            '2634' => ['RM VIA GIULIO AGRICOLA','ROMA'],
            '2766' => ['ROMA VIA ASTRI','ROMA'],
            '2769' => ['MI VIA CARONCINI','MILANO'],
            '2799' => ['MILANO VIA BERTANI','MILANO'],
            '2803' => ['RM BRITANNIA','ROMA'],
            '2891' => ['MI VIA COSSERIA','MILANO'],
            '2904' => ['MI GIOVANNI DA MILANO','MILANO'],
            '2939' => ['Milano San Michele del Carso','MILANO'],
            '2940' => ['Express Milano V.le Piceno','MILANO'],
            '3107' => ['SHELL-MI OHM','MILANO'],
            '3185' => ['ROMA VIALE SOMALIA','ROMA'],
            '3268' => ['ROMA VIA CIVININI','ROMA'],
            '3293' => ['MILANO PONTE SEVESO','MILANO'],
            '3302' => ['MILANO CADORNA','MILANO'],
            '3308' => ['ROMA VIA QUADRIO','ROMA'],
            '3334' => ['ROMA VIALE CROCCO','ROMA'],
            '3341' => ['MILANO SAN VITO','MILANO'],
            '3356' => ['ROMA VIA DEI GIARDINETTI','ROMA'],
            '3359' => ['Roma Via Alessandria','ROMA'],
            '3365' => ['ROMA VIA DEL VIMINALE','ROMA'],
            '3390' => ['Milano Via Fontana','MILANO'],
            '3391' => ['ROMA VIA PO','ROMA'],
            '3398' => ['ROMA L.GO LUCIO APULEIO','ROMA'],
            '3411' => ['ROMA VIA DEL GESU\'','ROMA'],
            '3414' => ['ROMA V.E. ORLANDO','ROMA'],
            '3422' => ['MILANO PIAZZA SANTO STEFANO','MILANO'],
            '3423' => ['MILANO PIAZZA CINCINNATO','MILANO'],
            '3424' => ['MILANO VIA ALGAROTTI','MILANO'],
            '3427' => ['MILANO VIA ALSERIO','MILANO'],
            '3429' => ['MILANO VIA ANCONA','MILANO'],
            '3455' => ['ROMA VIA METAURO','ROMA'],
            '3491' => ['ROMA PORTA CASTELLO','ROMA'],
            '3508' => ['ROMA_NICOSIA','ROMA'],
            '3513' => ['MY CHEF - CALDERA','MILANO'],
            '3527' => ['MILANOFIAMMA','MILANO'],
            '3530' => ['MY CHEF SALARIA EST','ROMA'],
            '3624' => ['RM Teatro Marcello','ROMA'],
            '3625' => ['MI VIA MONTEVIDEO','MILANO'],
            '3626' => ['MI - CORSO SEMPIONE','MILANO'],
            '3627' => ['MI LARGO ZANDONAI','MILANO'],
            '3628' => ['FI - CAREGGI','FIRENZE'],
            '3646' => ['FI - CARDUCCI','FIRENZE'],
            '3647' => ['FI - PRATO','FIRENZE'],
            '3648' => ['FI - RUOTE','FIRENZE'],
            '3649' => ['FI - ROMANA','FIRENZE'],
            '3650' => ['FI - TASSO','FIRENZE'],
            '3651' => ['FI - DE GINORI','FIRENZE'],
            '3665' => ['FIRENZE RICASOLI','FIRENZE'],
            '3666' => ['FIRENZE ALBIZI','FIRENZE'],
            '3669' => ['FIRENZE MARCONI','FIRENZE'],
            '3686' => ['FIRENZE ZAMBRINI','FIRENZE'],
            '3687' => ['FIRENZE BARBIERI','FIRENZE'],
            '3688' => ['MILANO VIA LOMAZZO','MILANO'],
            '3700' => ['MILANOSANSIRO','MILANO'],
            '3730' => ['MILANO PORPORA','MILANO'],
            '3760' => ['RM TRIONFALE','ROMA'],
            '3808' => ['FIRENZE ALIGHIERI','FIRENZE'],
            '3842' => ['FIRENZE S. CATERINA SIENA','FIRENZE'],
            '3883' => ['ROMA BISCIONE','ROMA']
        ],
        'dates' => [
            '1607',
            '1608',
            '1609',
            '1610',
            '1611',
            '1612',
            '1701',
            '1702',
            '1703',
            '1704',
            '1705',
            '1706',
            '1707',
            '1708',
            '1709',
            '1710',
            '1711',
            '1712'
        ],
        'minutes' => 5,
        'description' => 'Bonus promozione Carrefour',
        'validFor' => '+90 days'
    ]
];
